#!/usr/bin/python3


"""
Usage: replicatemol <config_filename> <top_filename> <num_molecules>
"""

import sys
import string
from ReplicateMolecules import Replicate

if "--help" in sys.argv or len(sys.argv) != 4:
    print(__doc__)
    sys.exit(0)

Replicate(sys.argv[1], sys.argv[2], int(sys.argv[3]))
    
